name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate changelog
        id: changelog
        run: |
          echo "生成版本更新日志..."
          PREV_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
          if [ -z "$PREV_TAG" ]; then
            git log --pretty=format:"* %s" > CHANGELOG.md
          else
            git log --pretty=format:"* %s" $PREV_TAG..HEAD > CHANGELOG.md
          fi

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: StreamCap ${{ github.ref_name }}
          draft: false
          prerelease: false
          body_path: CHANGELOG.md

  build-windows:
    needs: create_release
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Prepare icon file
        run: |
          if (Test-Path -Path "assets\icon.ico") {
            New-Item -ItemType Directory -Force -Path "assets\images" | Out-Null
            Copy-Item -Path "assets\icon.ico" -Destination "assets\images\logo.ico" -Force
            Write-Host "Icon file copied to assets\images\logo.ico"
          } else {
            Write-Host "Warning: Icon file assets\icon.ico not found. Using default icon."
          }

      - name: Build Windows executable with dependencies (-D mode)
        run: |
          # 使用-D选项创建目录模式的打包
          if (Test-Path -Path "assets\images\logo.ico") {
            pyinstaller --name StreamCap -D --windowed --icon=assets/images/logo.ico main.py
          } else {
            pyinstaller --name StreamCap -D --windowed main.py
          }
          
          # 创建必要的目录和文件
          New-Item -ItemType Directory -Force -Path "dist\StreamCap\downloads" | Out-Null
          New-Item -ItemType Directory -Force -Path "dist\StreamCap\logs" | Out-Null
          New-Item -ItemType File -Force -Path "dist\StreamCap\logs\play_url.log" | Out-Null
          New-Item -ItemType File -Force -Path "dist\StreamCap\logs\streamget.log" | Out-Null
          
          # 复制资源文件夹到dist\StreamCap目录
          if (-not (Test-Path -Path "dist\StreamCap\assets")) {
            Copy-Item -Path "assets" -Destination "dist\StreamCap\" -Recurse -Force
          }
          if (-not (Test-Path -Path "dist\StreamCap\config")) {
            Copy-Item -Path "config" -Destination "dist\StreamCap\" -Recurse -Force
          }
          if (-not (Test-Path -Path "dist\StreamCap\locales")) {
            Copy-Item -Path "locales" -Destination "dist\StreamCap\" -Recurse -Force
          }
          
          Write-Host "Successfully built StreamCap with dependencies in directory mode"

      - name: Debug directory contents
        run: |
          Write-Host "dist\StreamCap directory structure:"
          Get-ChildItem -Path .\dist\StreamCap -Recurse -Depth 2 | Select-Object FullName

      - name: Create ZIP archive
        run: |
          # 压缩整个dist\StreamCap目录
          Compress-Archive -Path "dist\StreamCap\*" -DestinationPath "StreamCap-Windows.zip" -Force

      - name: Upload Windows build
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./StreamCap-Windows.zip
          asset_name: StreamCap-Windows.zip
          asset_content_type: application/zip

  build-macos:
    needs: create_release
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Prepare icon file
        run: |
          if [ -f "assets/icon.ico" ]; then
            mkdir -p assets/images
            cp assets/icon.ico assets/images/logo.ico
            echo "Icon file copied to assets/images/logo.ico"
          else
            echo "Warning: Icon file assets/icon.ico not found. Using default icon."
          fi

      - name: Build macOS app with dependencies (-D mode)
        run: |
          # 使用-D选项创建目录模式的打包
          if [ -f "assets/images/logo.icns" ]; then
            pyinstaller --name StreamCap -D --windowed --icon=assets/images/logo.icns main.py
          else
            pyinstaller --name StreamCap -D --windowed main.py
          fi
          
          # 创建必要的目录和文件
          mkdir -p dist/StreamCap/downloads
          mkdir -p dist/StreamCap/logs
          touch dist/StreamCap/logs/play_url.log
          touch dist/StreamCap/logs/streamget.log
          
          # 复制资源文件夹到dist/StreamCap目录
          if [ ! -d "dist/StreamCap/assets" ]; then
            cp -r assets dist/StreamCap/
          fi
          if [ ! -d "dist/StreamCap/config" ]; then
            cp -r config dist/StreamCap/
          fi
          if [ ! -d "dist/StreamCap/locales" ]; then
            cp -r locales dist/StreamCap/
          fi
          
          echo "Successfully built StreamCap with dependencies in directory mode"

      - name: Debug directory contents
        run: |
          echo "dist/StreamCap directory structure:"
          find ./dist/StreamCap -maxdepth 2

      - name: Create DMG
        run: |
          # 直接从dist/StreamCap创建DMG
          hdiutil create -volname StreamCap -srcfolder dist/StreamCap -ov -format UDZO StreamCap-macOS.dmg

      - name: Upload macOS build
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./StreamCap-macOS.dmg
          asset_name: StreamCap-macOS.dmg
          asset_content_type: application/octet-stream

  build-docker:
    needs: create_release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/streamcap:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/streamcap:${{ github.ref_name }} 